---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: les-quiromanciers
spec:
  selector:
    matchLabels:
      app: les-quiromanciers
  template:
    metadata:
      labels:
        app: les-quiromanciers
    spec:
      containers:
        - name: les-quiromanciers
          image: gcr.io/neomail-258716/les-quiromanciers:latest
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: les-quiromanciers
spec:
  type: LoadBalancer
  selector:
    app: les-quiromanciers
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
