version: "3.7"

services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    volumes:
      - "./data:/home/data/"
    ports:
      - "5000:5000"

    stdin_open: true
    tty: true
    networks:
      - default

  streamlit:
    container_name: streamlit
    build:
      context: .
      dockerfile: ./docker/streamlit/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - "./data:/home/data/"

    stdin_open: true
    tty: true
    networks:
      - default
