apiVersion: batch/v1
kind: Job
metadata:
  name: les-quiromanciers
  namespace: les-quiromanciers
spec:
  template:
    spec:
      containers:
        - name: les-quiromanciersxxxxx
          image: gcr.io/neomail-258716/les-quiromanciers:latest
          imagePullPolicy: Always
          env:
            - name: PROJECT_ID
              value: "neomail-258716"
            - name: ENVIRONMENT
              value: PRODUCTION
          volumeMounts:
            - mountPath: "/files"
              name: nfs-lq

      volumes:
        - name: nfs-lq
          persistentVolumeClaim:
            claimName: nfs-lq
      restartPolicy: Never
