apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-01-les-quiromanciers
  namespace: les-quiromanciers
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
