apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-lq
  namespace: les-quiromanciers
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs-lq/shared
    server: 172.26.165.26
