apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-lq
  namespace: les-quiromanciers
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
