apiVersion: v1
kind: Pod
metadata:
  name: les-quiromanciers
spec:
  containers:
    - name: les-quiromanciersxxxxx
      image: gcr.io/neomail-258716/les-quiromanciers:latest
      volumeMounts:
        - mountPath: "/mnt/shared"
          name: nfs-lq
  volumes:
    - name: nfs-lq
      persistentVolumeClaim:
        claimName: nfs-lq
        readOnly: false
