apiVersion: v1
kind: Service
metadata:
  name: les-quiromanciers
spec:
  type: LoadBalancer
  selector:
    app: les-quiromanciers
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
